config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}
  get 'products/index'
  root 'products#index'
  # resources :products

  resources :products 
  resources :carts 
  resources :charges
  post 'carts/callback'

  authenticated do
    root to: "products#index", as: :authenticated_root
  end

  get 'products/:id/add_to_cart' => 'carts#add_to_cart', :as => 'add_to_cart'
  get 'carts/:id/remove' => 'carts#remove', :as => 'remove'
  get 'my_order' => 'carts#my_order', :as => 'my_order'
  
  get 'product_status' => 'products#product_status', :as => 'product_status'
  get 'seller_product' => 'products#seller_product', :as => 'seller_product'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :order
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:callback]

  def index
    if current_user.orders.where(status: false).exists?
      @order = current_user.orders.where(status: false).last
      @carts = @order.carts.all
    else
      redirect_to products_path, :notice =>"product are not avaliable"
    end 
  end

  def my_order
    @orders=current_user.orders.where(:status => true)
  end

  def show
    @order=Order.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "show"   # Excluding ".pdf" extension.
      end
    end
  end


  def callback
    if params[:data][:object][:metadata][:Order]
      @order=Order.find(params[:data][:object][:metadata][:Order])
      @order.update_attributes(:status => :true)
      user=User.find(@order.user_id)
      UserMailer.sample_email(user).deliver_now
      @order.carts.each do |p|
        @product=Product.find(p.product_id)
        @user=User.find(@product.user_id)
        UserMailer.seller_email(@user).deliver_now
      end
      # respond_to do |format|
      #    format.xml 
        # flash[:notice] = "product placed succesfully" 
      # end
    end
    # byebug
    # redirect_to root_path,:notice =>"product placed succesfully"  and return
    render 'callback'
  end

  def add_to_cart
    @product = Product.find(params[:id]) 
    if current_user.orders.where(status: false).exists?
      @order = current_user.orders.last
    else
      @order = current_user.orders.new
      @order.save
    end  
    if @order.carts.exists?
      @order.carts.each do |c|
        if c.product_id == @product.id
          c.increment! :quantity
          @a = @product.price*c.quantity
          c.update_attributes(:price => @a)
          redirect_to products_path,:notice =>"product add succesfully"
          return
        end
      end
      cart_make
    else
      cart_make
    end
  end

  def cart_make
    @cart = @order.carts.new
    @cart.quantity = "1"
    @cart.price = @product.price
    @cart.product_id = @product.id
    @cart.save
    redirect_to products_path,:notice =>"product add succesfully"
  end

  def remove
    @cart=Cart.find(params[:id])
    if @cart.destroy
      redirect_to carts_path
    end
    # if current_user.orders.where(:status => false).exists?
    #   p=current_user.orders.where(:status => false).last
      # p.carts.each do |p|
      #   byebug
      
      #   @cart=Cart.find(params[:id])
      #   if p.id == @cart.id
      #     @cart.destroy
      #     redirect_to carts_path   
      #   end
      # end
    # end
  end

  def update
    @cart=Cart.find(params[:id])
    @cart.update_attributes(:quantity => params[:data])
    @product=Product.find(@cart.product_id)
    @a = @product.price*@cart.quantity
    @cart.update_attributes(:price => @a)
    respond_to do |format|
      format.js 
      format.html { redirect_to carts_path, notice: "Save comment completed!" } 
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<div id="cart_<%= cart.id %>">
  <% p=cart.product_id %>
  <% q=Product.find(p) %>

    <strong>image:- </strong><%= image_tag(q.avatar_url, height: '200', width: '150') if q.avatar? %><br />
    <strong>title:- </strong><%= q.title %><br />
    <strong>available:- </strong><%= q.available_quantity %><br />
    
    <div class="quantity_link", data-url = "<%= cart_path(cart.id) %>", data-id = "<%= cart.id.to_s %>">
      <strong>quantity:- </strong>
      <select  id="<%= 'quantity_' + cart.id.to_s %>" >
        <option><%= cart.quantity %></option>
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
      </select>
    </div><br />
    <strong>price:- </strong><%= cart.price %><br />
    <%= link_to 'remove', remove_path(cart)  %>
  <br />
</div>

app/views/carts/index.html.erb
<h1>cart_product</h1>

<div> 
  <% @carts.each do |cart| %>
    <%= render 'form', cart: cart %>
  <% end %>
</div>
<br />
  <%= link_to 'back', products_path %>
<br />

<%= render 'charges/new' %>

app/views/carts/my_order.html.erb
<h1>my_order</h1>
<table class = "table" >
  <tr>
    <th>order_id</th>
    <th>title</th>
    <th>payment</th>
  </tr>
 
  <% @orders.each do |order| %>
    <% p=order.carts.first %>
    <% pro=Product.find(p.product_id) %>
    <tr>
      <td><%= order.id %></td>
      <td><%= pro.title %></td>    
      <td> done </td>
      <td><%= link_to "Get PDF", cart_path(order, format: :pdf), target: "_blank" %></td>
    </tr>
  <% end %>
</table>

app/views/carts/show.pdf.erb
<!doctype html>
<% total=0 %>
<html>
  <head>
    <meta charset='utf-8' />
    <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
    <%= wicked_pdf_javascript_include_tag "number_pages" %>
  </head>
  <body onload='number_pages'>
    <div id="header">
      <table class = "table" >
        <tr>
          <th>Title</th>
          <th>quantity</th>
          <th>price</th>
          <th></th>
        </tr>
        <% @order.carts.each do |cart| %>

        <% @product=Product.find(cart.product_id) %>
          <tr>
            <td><%= @product.title %></td>
            <td><%= cart.quantity %></td>
            <td><%= cart.price %></td>
          </tr>
            <% total= total+ cart.price %>
        <% end %>
      </table>
    </div>

    <strong>total_price</strong><%= total %>
  </body>
</html>

app/views/carts/update.js.erb
$("#cart_"+<%= @cart.id %>).html("<%= j render 'carts/form', cart: @cart %>");