config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}
  get 'products/index'
  root 'products#index'
  # resources :products

  resources :products 
  resources :carts 
  resources :charges
  post 'carts/callback'

  authenticated do
    root to: "products#index", as: :authenticated_root
  end

  get 'products/:id/add_to_cart' => 'carts#add_to_cart', :as => 'add_to_cart'
  get 'carts/:id/remove' => 'carts#remove', :as => 'remove'
  get 'my_order' => 'carts#my_order', :as => 'my_order'
  
  get 'product_status' => 'products#product_status', :as => 'product_status'
  get 'seller_product' => 'products#seller_product', :as => 'seller_product'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :carts, dependent: :destroy
  belongs_to :user
  mount_uploader :avatar, AvatarUploader
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource
  
  def index
    if current_user.has_role? :seller
      seller_product_path
    else
      @products = Product.all
    end
  end

  
  def seller_product
    @products=current_user.products.all
  end


  def product_status
    @products=current_user.products
  end


  def show
    @product=Product.find(params[:id])
  end

  def edit
    @product=current_user.products.find(params[:id])
  end

  def update
    @product=current_user.products.find(params[:id])
    p=@product.all_quantity
    @product.all_quantity=(p)+(params[:product][:available_quantity]).to_i

    if @product.update(product_params)
      redirect_to seller_product_path
    else
      render 'new'
    end
  end

  def new
    @product=current_user.products.new
  end

  def create
    @product = current_user.products.new(product_params)
    @product.all_quantity=params[:product][:available_quantity]
    if @product.save
      redirect_to seller_product_path
    else
      render 'new'
    end
  end

  def destroy
    @product=current_user.products.find(params[:id])
    if @product.destroy
      redirect_to seller_product_path
    else
      render 'new'
    end
  end

  private
  def product_params
    params.require(:product).permit(:title, :description, :price, :avatar, :available_quantity)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%#= form_with scope: :product, url: products_path, local:true do |f| %>
<%#= form_with @product do |f| %>
<%= form_with(model:@product) do |f| %>
  
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>

  <p>
    <%= f.label :available_quantity %><br>
    <%= f.text_field :available_quantity %>
  </p>

  <p>
  <%= f.label :avatar %><br>
  <%= f.file_field :avatar %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/products/edit.html.erb
<h3>edit_page</h3>

<%= render 'form' %>

app/views/products/index.html.erb
<h1>Products_index</h1>
<%= link_to 'cart', carts_path %><br />
<%= link_to 'my_order', my_order_path %>
<table class = "table" >
  <tr>
    <th>image</th>
    <th>Title</th>
    <th>description</th>
    <th>price</th>
    <th></th>
  </tr>
 
  <% @products.each do |product| %>
    <tr>
      <td><%= image_tag(product.avatar_url, height: '200', width: '150') if product.avatar? %></td>
      <td><%= product.title %></td>
      <td><%= product.description %></td>
      <td><%= product.price %></td>
      <td><%= link_to 'Show', product_path(product) %></td>
      <% if  product.available_quantity > 0 %>
        <td><%= link_to 'add_to_cart', add_to_cart_path(product) %></td>
      <% else %>
        <td> comming_soon </td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/products/new.html.erb
<h3>add_products</h3>

<%= render 'form' %>

app/views/products/product_status.html.erb
<h1>Products_status</h1>
<% total_sell=0 %>
<%= link_to 'back', seller_product_path %>


<table class = "table" >
  <tr>
    <th>image</th>
    <th>Title</th>
    <th>price</th>
    <th>available_quantity</th>
    <th>product_sell</th>
    <th>total_price</th>
    <th></th>
  </tr>
 
  <% @products.each do |product| %>
    <tr>
    <% p=product.all_quantity-product.available_quantity %>
      <td><%= image_tag(product.avatar_url, height: '200', width: '150') if product.avatar? %></td>
      <td><%= product.title %></td>
      <td><%= product.price %></td>
      <td><%= product.available_quantity %></td>
      <td><%= p %></td>
      <td><%= p*product.price %></td>
    </tr>
    <% total_sell=total_sell+p*product.price %>
  <% end %>
  
</table>
<strong>total_amount:- </strong><%= total_sell %>

app/views/products/seller_product.html.erb
<h1>seller_product</h1>
<%= link_to 'add_product', new_product_path %><br />
<%= link_to 'product_status', product_status_path %>

<table class = "table" >
  <tr>
    <th>image</th>
    <th>Title</th>
    <th>description</th>
    <th>mrp</th>
    <th>available_quantity</th>
    <th></th>
  </tr>
 
  <% @products.each do |product| %>
    <tr>
      <td><%= image_tag(product.avatar_url, height: '200', width: '150') if product.avatar? %></td>
      <td><%= product.title %></td>
      <td><%= product.description %></td>
      <td><%= product.price %></td>
      <td><%= product.available_quantity %></td>
      <td><%= link_to 'Show', product_path(product) %></td>
      <td><%= link_to 'edit', edit_product_path(product) %></td>
      <td><%= link_to 'Destroy', product_path(product), method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/products/show.html.erb
<p>
  <strong>image:-</strong>
  <%= image_tag(@product.avatar_url, height: '200', width: '150') if @product.avatar? %>
</p>

<p>
  <strong>title</strong>
  <%= @product.title %>
</p>

<p>
  <strong>description</strong>
  <%= @product.description %>
</p>

<p>
  <strong>price</strong>
  <%= @product.price %>
</p>
      